# Generated by Django 4.1.7 on 2023-02-16 12:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_category', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('create_timestamp', models.DateTimeField()),
                ('timestamp', models.DateTimeField()),
                ('language', models.CharField(max_length=50)),
                ('wiki', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('auxiliary_text', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), null=True, size=None)),
                ('category', models.ManyToManyField(blank=True, to='api_app.category')),
            ],
        ),
    ]
