# Generated by Django 4.1.7 on 2023-02-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_alter_quote_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='quotes', to='api_app.category'),
        ),
    ]
